# NETFLIX
---
0. NETFILX 소개
    - ....
1. 데이터 수집
    - Netflix_Data
    - Netflix_Original Data
    - Rating_Data
    - Netflix_Data + Netflix_Original Data + Rating_Data
2. 데이터 전처리
    - 결측치 수정 및 제거
    - Feature engineering
3. 데이터 EDA
    - ..
4. 결론

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

import warnings 
warnings.filterwarnings(action='ignore')

## 0. NETFILX 소개

## 1. 데이터 수집
---

### Netflix_Data
</br>

__✅COLUMNS__

<br></br>

| SHOW_ID | 영화나 티비쇼의 고유번호  |
| --- | --- |
| TYPE | 영화인지 티비쇼인지 구별 |
| TITLE | 영화, 티비쇼의 제목 |
| DIRECTOR | 영화감독 |
| CAST | 영화, 쇼에 출연한 배우들 |
| COUNTRY | 영화나 쇼가 제작된 나라 |
| DATE_ADDED | 넷플릭스에 드라마나 영화가 방영된 날짜. 2008.01 ~ 2021.09.25 |
| RELEASE_YEAR | 실제 드라마나 영화가 방영된 연도. 1925 ~ 2021 |
| RATING | 영화/쇼의 시청 등급 |
| DURATION | 방영기간 |
| LISTED_IN | 장르 |
| DESCRIPTION | 줄거리 |

In [2]:
path = './data'
Net_df = pd.read_csv(path+"/fixed_netflix_df.csv")
Net_df.head()

,show_id,type,director,title,cast,country,date_added,description,duration,listed_in,rating,release_year
0,s1,Movie,Kirsten Johnson,Dick Johnson Is Dead,"Michael Hilow, Dick Johnson, Chad Knorr, Vasth...",United States,"September 25, 2021","As her father nears the end of his life, filmm...",90 min,Documentaries,PG-13,2020
1,s2,TV Show,Nosipho Dumisa,Blood & Water,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021","After crossing paths at a party, a Cape Town t...",2 Seasons,"International TV Shows, TV Dramas, TV Mysteries",TV-MA,2021
2,s3,TV Show,Julien Leclercq,Ganglands,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",France,"September 24, 2021",To protect his family from a powerful drug lor...,1 Season,"Crime TV Shows, International TV Shows, TV Act...",TV-MA,2021
3,s4,TV Show,Jacquelyn C. Migdal,Jailbirds New Orleans,NONE,United States,"September 24, 2021","Feuds, flirtations and toilet talk go down amo...",1 Season,"Docuseries, Reality TV",TV-MA,2021
4,s5,TV Show,Raghav Subbu,Kota Factory,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",In a city of coaching centers known to train I...,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",TV-MA,2021

### Netflix_Original Data
__✅ COLUMNS__

In [3]:
OG = pd.read_csv("./data/NetflixOriginals.csv", encoding="ISO-8859-1")
OG = OG["Title"].tolist()
OG[:10]

['Enter the Anime',
 'Dark Forces',
 'The App',
 'The Open House',
 'Kaali Khuhi',
 'Drive',
 'Leyla Everlasting',
 'The Last Days of American Crime',
 'Paradox',
 'Sardar Ka Grandson']

### Rating_Data
__✅ COLUMNS__

In [4]:
Rating_df = pd.read_csv("./data/Netflix_Rating.csv")
Rating_df.head()

,Title,Avg,Total,Total_males,Total_Females,All_below_18,All_18_29,All_30_44,All_over_45,Males_below_18,...,Males_rank_below_18,Males_rank_18_29,Males_rank_30_44,Males_rank_over_45,Females_rank_below_18,Females_rank_18_29,Females_rank_30_44,Females_rank_over_45,Avg_rank_males,Avg_rank_Females
0,Dick Johnson Is Dead,7.4,6241.0,3780.0,592.0,12.0,1050.0,2321.0,817.0,10.0,...,7.9,7.7,7.4,7.1,8.0,7.8,7.4,7.3,7.4,7.5
1,Blood & Water,6.7,2952.0,603.0,867.0,10.0,416.0,644.0,281.0,4.0,...,5.5,6.6,5.9,4.9,5.0,6.9,7.0,7.0,5.9,7.0
2,Ganglands,7.0,2349.0,1297.0,117.0,1.0,99.0,574.0,648.0,1.0,...,6.0,6.9,6.8,7.0,0.0,5.8,6.9,7.0,6.9,7.0
3,Jailbirds New Orleans,6.7,194.0,57.0,60.0,0.0,19.0,63.0,30.0,0.0,...,0.0,6.4,6.3,6.6,0.0,6.2,6.9,6.9,6.5,6.9
4,Kota Factory,9.3,66527.0,19278.0,984.0,144.0,10004.0,5687.0,340.0,134.0,...,9.6,9.2,8.5,6.4,4.3,9.2,7.5,5.7,9.0,8.5

### Netflix_Data + Netflix_Original Data +  Rating_Data

In [5]:
# Netflix_Data + Netflix_Original Data 
og = []
for name in Net_df.title.values:
    if name in OG:
        og.append(1)
    else:
        og.append(0)

Net_df["Original"] = og
Net_df["Original"].value_counts()

0    8301
1     506
Name: Original, dtype: int64

In [6]:
total_df = pd.merge(Net_df, Rating_df, left_on= "title", right_on= "Title")
total_df.head()

,show_id,type,director,title,cast,country,date_added,description,duration,listed_in,...,Males_rank_below_18,Males_rank_18_29,Males_rank_30_44,Males_rank_over_45,Females_rank_below_18,Females_rank_18_29,Females_rank_30_44,Females_rank_over_45,Avg_rank_males,Avg_rank_Females
0,s1,Movie,Kirsten Johnson,Dick Johnson Is Dead,"Michael Hilow, Dick Johnson, Chad Knorr, Vasth...",United States,"September 25, 2021","As her father nears the end of his life, filmm...",90 min,Documentaries,...,7.9,7.7,7.4,7.1,8.0,7.8,7.4,7.3,7.4,7.5
1,s2,TV Show,Nosipho Dumisa,Blood & Water,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021","After crossing paths at a party, a Cape Town t...",2 Seasons,"International TV Shows, TV Dramas, TV Mysteries",...,5.5,6.6,5.9,4.9,5.0,6.9,7.0,7.0,5.9,7.0
2,s3,TV Show,Julien Leclercq,Ganglands,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",France,"September 24, 2021",To protect his family from a powerful drug lor...,1 Season,"Crime TV Shows, International TV Shows, TV Act...",...,6.0,6.9,6.8,7.0,0.0,5.8,6.9,7.0,6.9,7.0
3,s4,TV Show,Jacquelyn C. Migdal,Jailbirds New Orleans,NONE,United States,"September 24, 2021","Feuds, flirtations and toilet talk go down amo...",1 Season,"Docuseries, Reality TV",...,0.0,6.4,6.3,6.6,0.0,6.2,6.9,6.9,6.5,6.9
4,s5,TV Show,Raghav Subbu,Kota Factory,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",In a city of coaching centers known to train I...,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",...,9.6,9.2,8.5,6.4,4.3,9.2,7.5,5.7,9.0,8.5

## 2. 데이터 전처리

- 결측치 수정 및 제거
    - 결측치 확인 및 크롤링으로 추가
    - 확인되지 않는 행 제거
    - 사용하지 않는 컬럼 제거
- Feature engineering
    - 영화 관람 등급, 티비 관람 등급
    - score(평점, 리뷰 수)...

### 결측치 수정 및 제거

In [7]:
# 결측치 이미 채움
total_df[total_df['rating'] == '74 min']

total_df[total_df['rating'] == '66 min']

total_df[total_df['rating'] == '84 min']

index = total_df[total_df['rating'] == '66 min'].index 
total_df.loc[index,'duration'] = total_df.loc[index,'rating']
total_df.loc[index,'rating'] = np.nan

index = total_df[total_df['rating'] == '74 min'].index
total_df.loc[index,'duration'] = total_df.loc[index,'rating']
total_df.loc[index,'rating'] = np.nan

index = total_df[total_df['rating'] == '84 min'].index
total_df.loc[index,'duration'] = total_df.loc[index,'rating']
total_df.loc[index,'rating'] = np.nan

total_df['rating'].unique()

total_df.isnull().sum()

show_id                   0
type                      0
director                  0
title                     0
cast                      0
country                   0
date_added               10
description               0
duration                  0
listed_in                 0
rating                    7
release_year              0
Original                  0
Title                     0
Avg                       0
Total                     0
Total_males               0
Total_Females             0
All_below_18              0
All_18_29                 0
All_30_44                 0
All_over_45               0
Males_below_18            0
Males_18_29               0
Males_30_44               0
Males_over_45             0
Females_below_18          0
Females_18_29             0
Females_30_44             0
Females_over_45           0
Title_ID                  0
All_rank_below_18         0
All_rank_18_29            0
All_rank_30_44            0
All_rank_over_45          0
Males_rank_below_18       0
Males_rank_18_29          0
Males_rank_30_44          0
Males_rank_over_45        0
Females_rank_below_18     0
Females_rank_18_29        0
Females_rank_30_44        0
Females_rank_over_45      0
Avg_rank_males            0
Avg_rank_Females          0
dtype: int64

In [8]:
# NOT FOUND 제거
total_df.drop(total_df[total_df["Title_ID"] == "NOT FOUND"].index, inplace=True)
total_df.head()

,show_id,type,director,title,cast,country,date_added,description,duration,listed_in,...,Males_rank_below_18,Males_rank_18_29,Males_rank_30_44,Males_rank_over_45,Females_rank_below_18,Females_rank_18_29,Females_rank_30_44,Females_rank_over_45,Avg_rank_males,Avg_rank_Females
0,s1,Movie,Kirsten Johnson,Dick Johnson Is Dead,"Michael Hilow, Dick Johnson, Chad Knorr, Vasth...",United States,"September 25, 2021","As her father nears the end of his life, filmm...",90 min,Documentaries,...,7.9,7.7,7.4,7.1,8.0,7.8,7.4,7.3,7.4,7.5
1,s2,TV Show,Nosipho Dumisa,Blood & Water,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021","After crossing paths at a party, a Cape Town t...",2 Seasons,"International TV Shows, TV Dramas, TV Mysteries",...,5.5,6.6,5.9,4.9,5.0,6.9,7.0,7.0,5.9,7.0
2,s3,TV Show,Julien Leclercq,Ganglands,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",France,"September 24, 2021",To protect his family from a powerful drug lor...,1 Season,"Crime TV Shows, International TV Shows, TV Act...",...,6.0,6.9,6.8,7.0,0.0,5.8,6.9,7.0,6.9,7.0
3,s4,TV Show,Jacquelyn C. Migdal,Jailbirds New Orleans,NONE,United States,"September 24, 2021","Feuds, flirtations and toilet talk go down amo...",1 Season,"Docuseries, Reality TV",...,0.0,6.4,6.3,6.6,0.0,6.2,6.9,6.9,6.5,6.9
4,s5,TV Show,Raghav Subbu,Kota Factory,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",In a city of coaching centers known to train I...,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",...,9.6,9.2,8.5,6.4,4.3,9.2,7.5,5.7,9.0,8.5

In [9]:
total_df = total_df.reset_index(drop=True)

In [10]:
# 사용하지 않는 컬럼 제거
# date_added
# show_id
# desciption
# Title_ID

In [11]:
total_df.drop(["date_added", "show_id", "description", "Title_ID"], axis = 1, inplace=True)
total_df.head()

,type,director,title,cast,country,duration,listed_in,rating,release_year,Original,...,Males_rank_below_18,Males_rank_18_29,Males_rank_30_44,Males_rank_over_45,Females_rank_below_18,Females_rank_18_29,Females_rank_30_44,Females_rank_over_45,Avg_rank_males,Avg_rank_Females
0,Movie,Kirsten Johnson,Dick Johnson Is Dead,"Michael Hilow, Dick Johnson, Chad Knorr, Vasth...",United States,90 min,Documentaries,PG-13,2020,1,...,7.9,7.7,7.4,7.1,8.0,7.8,7.4,7.3,7.4,7.5
1,TV Show,Nosipho Dumisa,Blood & Water,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries",TV-MA,2021,0,...,5.5,6.6,5.9,4.9,5.0,6.9,7.0,7.0,5.9,7.0
2,TV Show,Julien Leclercq,Ganglands,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",France,1 Season,"Crime TV Shows, International TV Shows, TV Act...",TV-MA,2021,0,...,6.0,6.9,6.8,7.0,0.0,5.8,6.9,7.0,6.9,7.0
3,TV Show,Jacquelyn C. Migdal,Jailbirds New Orleans,NONE,United States,1 Season,"Docuseries, Reality TV",TV-MA,2021,0,...,0.0,6.4,6.3,6.6,0.0,6.2,6.9,6.9,6.5,6.9
4,TV Show,Raghav Subbu,Kota Factory,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",TV-MA,2021,0,...,9.6,9.2,8.5,6.4,4.3,9.2,7.5,5.7,9.0,8.5

In [12]:
total_df[total_df["rating"].isnull()]

,type,director,title,cast,country,duration,listed_in,rating,release_year,Original,...,Males_rank_below_18,Males_rank_18_29,Males_rank_30_44,Males_rank_over_45,Females_rank_below_18,Females_rank_18_29,Females_rank_30_44,Females_rank_over_45,Avg_rank_males,Avg_rank_Females
5411,Movie,Louis C.K.,Louis C.K. 2017,Louis C.K.,United States,74 min,Movies,NaN,2017,0,...,8.0,7.7,7.5,7.3,0.0,7.5,7.4,5.7,7.5,7.2
5655,Movie,Louis C.K.,Louis C.K.: Hilarious,Louis C.K.,United States,84 min,Movies,NaN,2010,0,...,10.0,8.5,8.4,8.0,0.0,8.4,8.3,8.0,8.4,8.3
5674,Movie,Louis C.K.,Louis C.K.: Live at the Comedy Store,Louis C.K.,United States,66 min,Movies,NaN,2015,0,...,8.0,7.9,7.7,7.6,0.0,8.0,7.7,7.6,7.8,7.7
5845,Movie,Lauren Dellara,13TH: A Conversation with Oprah Winfrey & Ava ...,"Oprah Winfrey, Ava DuVernay",English,37 min,Movies,NaN,2017,0,...,0.0,7.2,6.5,6.2,0.0,7.5,7.6,8.3,6.6,7.8
6666,TV Show,Kazuya Murata,Gargantia on the Verdurous Planet,"Kaito Ishikawa, Hisako Kanemoto, Ai Kayano, Ka...",Japan,1 Season,"Anime Series, International TV Shows",NaN,2013,0,...,0.0,7.4,7.3,7.5,0.0,7.9,7.7,6.2,7.3,7.7
7140,TV Show,Wayne Hope,Little Lunch,"Flynn Curry, Olivia Deeble, Madison Lu, Oisín ...",Australia,1 Season,"Kids' TV, TV Comedies",NaN,2015,0,...,8.0,7.9,7.7,8.5,7.0,7.9,8.4,8.1,8.1,8.3
7357,Movie,Alessandro Pepe,My Honor Was Loyalty,"Leone Frisa, Paolo Vaccarino, Francesco Miglio...",Italy,115 min,Dramas,NaN,2015,0,...,10.0,3.8,4.1,4.3,0.0,4.6,5.4,3.6,4.2,4.5

### Feature engineering

In [13]:
df['country']

NameError: name 'df' is not defined

type columns
- 영화: 0
- 티비쇼: 1

In [ ]:
def type_col(col):
    if col == 'Movie':
        return 0
    else:
        return 1

In [ ]:
df['type'] = df["type"].apply(type_col)
df

rating col
- 전체관람가('G', 'PG', 'TV-Y', 'TV-7', 'TV-Y7-FV', 'TV-G'): 0
- 12,15세 관람가('PG-13', 'TV-PG', 'TV-14'): 1
- 15, 청불('R', 'NC-17', 'NR', 'UR', 'TV-MA'): 2

In [ ]:
def rating_col(col):
    if col in ['G', 'PG', 'TV-Y','TV-Y7', 'TV-Y7-FV', 'TV-G']:
        return 0
    elif col in ['PG-13', 'TV-PG', 'TV-14']:
        return 1
    elif col in ['R', 'NC-17', 'NR', 'UR', 'TV-MA']:
        return 2
    else:
        return col

In [ ]:
df['rating'] = df["rating"].apply(rating_col)
df['rating']

duration컬럼에서 rating으로 밀린 항목 원래대로 복구

In [ ]:
df[df['rating'] == '74 min']

df[df['rating'] == '66 min']

df[df['rating'] == '84 min']

index = df[df['rating'] == '66 min'].index 
df.loc[index,'duration'] = df.loc[index,'rating']
df.loc[index,'rating'] = np.nan

index = df[df['rating'] == '74 min'].index
df.loc[index,'duration'] = df.loc[index,'rating']
df.loc[index,'rating'] = np.nan

index = df[df['rating'] == '84 min'].index
df.loc[index,'duration'] = df.loc[index,'rating']
df.loc[index,'rating'] = np.nan

df['rating'].unique()

duration col

In [ ]:
df.isnull().sum()

In [ ]:
# min 열만 가져오기
duration_col = df['duration'].str.endswith('min')

In [ ]:
df[duration_col]

In [ ]:
plt.figure(figsize=(30,15))
plt.hist(df[duration_col]['duration'])

In [ ]:
aa =df.loc[df['duration'].str.endswith('min'),'duration'] 
aa = [int(x[:-4]) for x in aa] 
plt.hist(aa) 
plt.xticks([0,30,60,90,120,150,180,210])

In [ ]:
plt.boxplot(aa)

In [ ]:
# listed_in columns을 중복제거 후 ','로 split해서 딕셔너리에 저장
# 장르별 duration 확인
listin = df['listed_in'].dropna().unique()

listin_list = []
for x in listin:
    list_1 = x.split(',')
    for y in list_1:
        if y.strip() in listin_list:
            continue
        else:
            listin_list.append(y.strip())
listin_list
df['listed_in']  = df['listed_in'].apply(lambda x: x.split(','))

bb = {x:[] for x in listin_list}
for x in range(len(df)):
   for y in df['listed_in'][x]:
       bb[y.strip()].append(df['duration'][x])

In [ ]:
bb

In [ ]:
# season, min 혼용된 listed_in 확인 
for i in bb:
    if all([x.endswith('min') for x in bb[i]]) != any([x.endswith('min') for x in bb[i]]):
        print(i)

In [ ]:
count=0
min_gen=[]
for i in bb:
    if all([x.endswith('min') for x in bb[i]]) == True:
        count+=1
        min_gen.append(i)


fig,ax = plt.subplots(3,3,figsize =(20,50))
plt.subplots_adjust(wspace = 0.3 , hspace = 0.3)

len(bb)
j=0
for i in bb:
    if j==9:break
    hist_data = [int(x.split(' ')[0]) for x in bb[i]]
    ax[j//3,j%3].hist(hist_data)
    ax[j//3,j%3].set_title(i)

    j+=1